const LA_THEATERS = [
  {
    name: "Brain Dead Studios",
    neighborhood: "Fairfax",
    type: "repertory",
    note: "Nightly one-off screenings — indie, cult & classics",
    opened: 1942,
    history: "Built in 1942 and originally operated as the Silent Movie Theatre, one of the last dedicated silent-film revival houses in the country. The theater closed following a tragic shooting in 1996 and passed through several subsequent operators. It reopened in 2020 under the Brain Dead clothing brand as a cultural hub combining a repertory cinema, café, and merchandise showroom.",
    url: "https://studios.wearebraindead.com",
    scheduleUrl: "https://studios.wearebraindead.com",
    searchUrl: (title, date) => `https://studios.wearebraindead.com`,
    fontFamily: "'Bebas Neue', sans-serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
  },
  {
    name: "Academy Museum",
    neighborhood: "Mid-Wilshire",
    type: "repertory",
    note: "Theatrical screenings at the Academy Museum of Motion Pictures",
    opened: 2021,
    history: "Opened September 30, 2021, in a renovated 1939 May Company building paired with a new glass sphere designed by Renzo Piano. The complex houses two cinemas: the 288-seat Ted Mann Theatre and the 1,000-seat David Geffen Theatre, which debuted with a live-orchestra screening of The Wizard of Oz. It is operated by the Academy of Motion Picture Arts and Sciences.",
    url: "https://www.academymuseum.org/en/calendar",
    scheduleUrl: "https://www.academymuseum.org/en/calendar",
    searchUrl: (title, date) => `https://www.academymuseum.org/en/calendar`,
    fontFamily: "'Space Mono', monospace",
    fontUrl: "https://fonts.googleapis.com/css2?family=Space+Mono:wght@700&display=swap",
  },
  {
    name: "New Beverly Cinema",
    neighborhood: "Mid-Wilshire",
    type: "repertory",
    note: "Quentin Tarantino's 35mm repertory house",
    opened: 1929,
    history: "Built in 1929 and used over the decades as a nightclub, Yiddish theatre, and adult film house before becoming a beloved repertory cinema in 1978. Since 2014 it has been owned and operated by Quentin Tarantino, who screens exclusively 35mm and 16mm film prints. It remains one of the few theaters in the world dedicated entirely to celluloid.",
    url: "https://www.thenewbev.com/",
    scheduleUrl: "https://www.thenewbev.com/",
    searchUrl: (title, date) => `https://www.thenewbev.com/`,
    fontFamily: "'Playfair Display', serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&display=swap",
  },
  {
    name: "Egyptian Theatre",
    neighborhood: "Hollywood",
    type: "repertory",
    note: "American Cinematheque — classic & foreign film",
    opened: 1922,
    history: "Opened October 18, 1922 with the world premiere of Douglas Fairbanks' Robin Hood — Hollywood's first-ever movie premiere. Built at a cost of $800,000 and inspired by public fascination with Egyptian antiquities, it set the template for the great movie palaces that followed. Now operated by Netflix as a restored historic cinema for premieres and repertory screenings.",
    url: "https://www.americancinematheque.com/egyptian-theatre/",
    scheduleUrl: "https://www.americancinematheque.com/now-showing/",
    searchUrl: (title, date) => `https://www.americancinematheque.com/now-showing/`,
    fontFamily: "'Cormorant Garamond', serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&display=swap",
  },
  {
    name: "Aero Theatre",
    neighborhood: "Santa Monica",
    type: "repertory",
    note: "American Cinematheque on the Westside",
    conservancyUrl: "https://www.laconservancy.org/learn/historic-places/aero-theatre/",
    opened: 1940,
    history: "Opened January 10, 1940, originally designed as a 24-hour cinema serving aircraft factory workers who labored around the clock during the wartime era. After closing in 2003 it was restored and reopened in 2005 by the American Cinematheque. It now specializes in classic, foreign, and revival film programming for the Westside.",
    url: "https://www.americancinematheque.com/aero-theatre/",
    scheduleUrl: "https://www.americancinematheque.com/now-showing/",
    searchUrl: (title, date) => `https://www.americancinematheque.com/now-showing/`,
    fontFamily: "'Cormorant Garamond', serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&display=swap",
  },
  {
    name: "Los Feliz 3",
    neighborhood: "Los Feliz",
    type: "arthouse",
    note: "American Cinematheque — classic & foreign film",
    opened: 1935,
    history: "Opened February 14, 1935 as a single-screen venue with 780 seats in the upscale Los Feliz neighborhood. It was triplexed in 1993, creating three screens of varying sizes. Today one auditorium is operated by American Cinematheque for repertory programming, while Vintage Cinemas manages the remaining screens.",
    url: "https://www.americancinematheque.com/los-feliz-theatre/",
    scheduleUrl: "https://www.americancinematheque.com/now-showing/",
    searchUrl: (title, date) => `https://www.americancinematheque.com/now-showing/`,
    fontFamily: "'Cormorant Garamond', serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&display=swap",
  },
  {
    name: "Landmark Nuart Theatre",
    neighborhood: "West LA",
    type: "arthouse",
    note: "Landmark Theatres' LA flagship",
    opened: 1930,
    history: "Opened August 16, 1930 with an original seating capacity of 660 in West Los Angeles. Since the early 1970s it has been a staple of the LA art-house scene, gaining fame for director's-cut screenings, midnight movies, and revival programming. It remains one of the city's most enduring single-screen independent cinemas.",
    url: "https://www.landmarktheatres.com/los-angeles/nuart-theatre",
    scheduleUrl: "https://www.landmarktheatres.com/los-angeles/nuart-theatre",
    searchUrl: (title, date) =>
      `https://www.google.com/search?q=${encodeURIComponent(title + ' showtimes Landmark Nuart Theatre')}`,
    fontFamily: "'Nunito', sans-serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Nunito:wght@700;800&display=swap",
  },
  {
    name: "Vista Theatre",
    neighborhood: "Los Feliz",
    type: "mainstream",
    note: "1923 single-screen gem, owned by Tarantino",
    conservancyUrl: "https://www.laconservancy.org/learn/historic-places/vista-theatre/",
    opened: 1923,
    history: "Opened October 16, 1923 as Lou Bard's Hollywood Theatre, featuring a Spanish Revival exterior and an elaborate Egyptian-style interior influenced by the 1922 discovery of Tutankhamen's tomb. Filmmaker Quentin Tarantino purchased it in 2021 and reopened it in 2023 with fully restored 35mm, 70mm, and VistaVision projection capabilities.",
    url: "https://www.vintagecinemas.com/vista/",
    scheduleUrl: "https://www.vintagecinemas.com/vista/",
    searchUrl: (title, date) =>
      `https://www.google.com/search?q=${encodeURIComponent(title + ' showtimes Vista Theatre Los Feliz')}`,
    fontFamily: "'Cinzel', serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Cinzel:wght@700&display=swap",
  },
  {
    name: "Billy Wilder Theatre",
    neighborhood: "Westwood",
    type: "repertory",
    note: "UCLA Film & Television Archive's repertory cinema",
    opened: 1971,
    history: "Opened in 1971 as part of the UCLA Extension building in Westwood. Renamed the Billy Wilder Theater in 2006 following a major renovation, in honor of the legendary filmmaker who spent the final decades of his life nearby. The 296-seat venue is the primary public screening space for the UCLA Film & Television Archive, one of the largest university film archives in the world, and hosts retrospectives, restorations, and visiting filmmaker programs.",
    url: "https://www.cinema.ucla.edu/events",
    scheduleUrl: "https://www.cinema.ucla.edu/events",
    searchUrl: (title, date) => `https://www.cinema.ucla.edu/events`,
    fontFamily: "'Roboto', sans-serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap",
  },
  {
    name: "Gardena Cinema",
    neighborhood: "Gardena",
    type: "arthouse",
    note: "South Bay repertory house screening cult, classic & world cinema",
    opened: 1946,
    history: "Originally opened in 1946 as a neighborhood single-screen theater serving the Gardena community in the South Bay. Over the decades it survived the multiplex era and transformed into a repertory destination specializing in cult films, foreign cinema, and 35mm screenings. It remains one of the few surviving single-screen independently operated theaters in the greater Los Angeles area.",
    url: "https://ticketing.uswest.veezi.com/sessions/?siteToken=he5nsxynkgmw2w1wvfey3mvh64",
    scheduleUrl: "https://ticketing.uswest.veezi.com/sessions/?siteToken=he5nsxynkgmw2w1wvfey3mvh64",
    searchUrl: (title, date) =>
      `https://www.google.com/search?q=${encodeURIComponent(title + ' showtimes Gardena Cinema')}`,
    fontFamily: "'Big Shoulders Display', sans-serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Big+Shoulders+Display:wght@700&display=swap",
  },
  {
    name: "Vidiots",
    neighborhood: "Eagle Rock",
    type: "repertory",
    note: "Beloved nonprofit video store reborn as a cinema",
    opened: 2022,
    openedLabel: "Re-Est.",
    history: "Vidiots began in 1985 as an independent video rental store in Santa Monica celebrated for its extraordinary collection of rare and eclectic titles. After closing in 2017, it was revived as a nonprofit foundation and reopened in 2022 inside the historic Eagle Theatre at 4901 Eagle Rock Blvd in Northeast Los Angeles. The new Vidiots combines a cinema programming classic, cult, and world films with a lending library of over 50,000 physical media titles.",
    url: "https://vidiotsfoundation.org/coming-soon/",
    scheduleUrl: "https://vidiotsfoundation.org/coming-soon/",
    searchUrl: (title, date) =>
      `https://www.google.com/search?q=${encodeURIComponent(title + ' showtimes Vidiots Eagle Rock')}`,
    fontFamily: "'Manrope', sans-serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Manrope:wght@700;800&display=swap",
  },
  {
    name: "Old Town Music Hall",
    neighborhood: "El Segundo",
    type: "repertory",
    note: "Silent-era classics with live Wurlitzer pipe organ",
    conservancyUrl: "https://www.laconservancy.org/learn/historic-places/old-town-music-hall/",
    opened: 1921,
    history: "Opened in 1921 as a neighborhood cinema in downtown El Segundo. Now one of the last theaters in the country to regularly screen silent films with live musical accompaniment — performed on its 1925 Robert Morton Mighty Wurlitzer pipe organ. The 185-seat single-screen venue programs a rotating repertory of silent and early sound-era classics.",
    url: "https://oldtownmusichall.org/",
    scheduleUrl: "https://tickets.oldtownmusichall.org/all-shows",
    searchUrl: (title, date) => `https://tickets.oldtownmusichall.org/all-shows`,
    fontFamily: "'Bebas Neue', sans-serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
  },
  {
    name: "The Culver Theater",
    neighborhood: "Culver City",
    type: "mainstream",
    note: "Classic screenings alongside new releases — Movie-Mad Mondays & Sunday Matinees",
    opened: 2017,
    history: "Opened in 2017 in the heart of downtown Culver City at 9500 Culver Boulevard. The modern single-screen theater features LED projection, HDR Cinema, and Dolby Atmos sound. Beyond its mainstream programming it hosts a growing slate of classic film events including the weekly Movie-Mad Mondays series, Sunday Matinees, and themed clubs.",
    url: "https://web.theculvertheater.com/",
    scheduleUrl: "https://web.theculvertheater.com/films",
    searchUrl: (title, date) => `https://web.theculvertheater.com/films`,
    fontFamily: "'Outfit', sans-serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Outfit:wght@600;700&display=swap",
  },
  {
    name: "Alamo Drafthouse DTLA",
    neighborhood: "Downtown",
    type: "mainstream",
    note: "Curated programming + mainstream",
    opened: 2019,
    history: "Opened July 2019 on the top floor of The Bloc, a downtown LA shopping complex. The 12-screen, 569-seat venue includes a screen equipped for 35mm projection and is part of the Alamo Drafthouse chain known for its dine-in format, craft drinks, and strict no-talking/no-phones policy. It offers both mainstream releases and curated specialty programming.",
    url: "https://drafthouse.com/los-angeles",
    scheduleUrl: "https://drafthouse.com/los-angeles",
    searchUrl: (title, date) => `https://drafthouse.com/los-angeles`,
    fontFamily: "'Jost', sans-serif",
    fontUrl: "https://fonts.googleapis.com/css2?family=Jost:wght@700&display=swap",
  },
];
