const LA_THEATERS = [
  {
    name: "Brain Dead Studios",
    neighborhood: "Fairfax",
    type: "repertory",
    note: "Nightly one-off screenings — indie, cult & classics",
    opened: 1942,
    history: "Built in 1942 and originally operated as the Silent Movie Theatre, one of the last dedicated silent-film revival houses in the country. The theater closed following a tragic shooting in 1996 and passed through several subsequent operators. It reopened in 2020 under the Brain Dead clothing brand as a cultural hub combining a repertory cinema, café, and merchandise showroom.",
    url: "https://studios.wearebraindead.com",
    scheduleUrl: "https://studios.wearebraindead.com",
    searchUrl: (title, date) => `https://studios.wearebraindead.com`,
  },
  {
    name: "Academy Museum",
    neighborhood: "Mid-Wilshire",
    type: "arthouse",
    note: "Theatrical screenings at the Academy Museum of Motion Pictures",
    opened: 2021,
    history: "Opened September 30, 2021, in a renovated 1939 May Company building paired with a new glass sphere designed by Renzo Piano. The complex houses two cinemas: the 288-seat Ted Mann Theatre and the 1,000-seat David Geffen Theatre, which debuted with a live-orchestra screening of The Wizard of Oz. It is operated by the Academy of Motion Picture Arts and Sciences.",
    url: "https://www.academymuseum.org/en/calendar",
    scheduleUrl: "https://www.academymuseum.org/en/calendar",
    searchUrl: (title, date) => `https://www.academymuseum.org/en/calendar`,
  },
  {
    name: "New Beverly Cinema",
    neighborhood: "Mid-Wilshire",
    type: "repertory",
    note: "Quentin Tarantino's 35mm repertory house",
    opened: 1929,
    history: "Built in 1929 and used over the decades as a nightclub, Yiddish theatre, and adult film house before becoming a beloved repertory cinema in 1978. Since 2014 it has been owned and operated by Quentin Tarantino, who screens exclusively 35mm and 16mm film prints. It remains one of the few theaters in the world dedicated entirely to celluloid.",
    url: "https://www.thenewbev.com/",
    scheduleUrl: "https://www.thenewbev.com/",
    searchUrl: (title, date) => `https://www.thenewbev.com/`,
  },
  {
    name: "Egyptian Theatre",
    neighborhood: "Hollywood",
    type: "repertory",
    note: "American Cinematheque — classic & foreign film",
    opened: 1922,
    history: "Opened October 18, 1922 with the world premiere of Douglas Fairbanks' Robin Hood — Hollywood's first-ever movie premiere. Built at a cost of $800,000 and inspired by public fascination with Egyptian antiquities, it set the template for the great movie palaces that followed. Now operated by Netflix as a restored historic cinema for premieres and repertory screenings.",
    url: "https://www.americancinematheque.com/egyptian-theatre/",
    scheduleUrl: "https://www.americancinematheque.com/now-showing/",
    searchUrl: (title, date) => `https://www.americancinematheque.com/now-showing/`,
  },
  {
    name: "Aero Theatre",
    neighborhood: "Santa Monica",
    type: "repertory",
    note: "American Cinematheque on the Westside",
    opened: 1940,
    history: "Opened January 10, 1940, originally designed as a 24-hour cinema serving aircraft factory workers who labored around the clock during the wartime era. After closing in 2003 it was restored and reopened in 2005 by the American Cinematheque. It now specializes in classic, foreign, and revival film programming for the Westside.",
    url: "https://www.americancinematheque.com/aero-theatre/",
    scheduleUrl: "https://www.americancinematheque.com/now-showing/",
    searchUrl: (title, date) => `https://www.americancinematheque.com/now-showing/`,
  },
  {
    name: "Los Feliz 3",
    neighborhood: "Los Feliz",
    type: "repertory",
    note: "American Cinematheque — classic & foreign film",
    opened: 1935,
    history: "Opened February 14, 1935 as a single-screen venue with 780 seats in the upscale Los Feliz neighborhood. It was triplexed in 1993, creating three screens of varying sizes. Today one auditorium is operated by American Cinematheque for repertory programming, while Vintage Cinemas manages the remaining screens.",
    url: "https://www.americancinematheque.com/los-feliz-theatre/",
    scheduleUrl: "https://www.americancinematheque.com/now-showing/",
    searchUrl: (title, date) => `https://www.americancinematheque.com/now-showing/`,
  },
  {
    name: "Nuart Theatre",
    neighborhood: "West LA",
    type: "arthouse",
    note: "Landmark Theatres' LA flagship",
    opened: 1930,
    history: "Opened August 16, 1930 with an original seating capacity of 660 in West Los Angeles. Since the early 1970s it has been a staple of the LA art-house scene, gaining fame for director's-cut screenings, midnight movies, and revival programming. It remains one of the city's most enduring single-screen independent cinemas.",
    url: "https://www.landmarktheatres.com/los-angeles/nuart-theatre",
    scheduleUrl: "https://www.landmarktheatres.com/los-angeles/nuart-theatre",
    searchUrl: (title, date) =>
      `https://www.google.com/search?q=${encodeURIComponent(title + ' showtimes Nuart Theatre')}`,
  },
  {
    name: "Vista Theatre",
    neighborhood: "Los Feliz",
    type: "arthouse",
    note: "1923 single-screen gem, owned by Tarantino",
    opened: 1923,
    history: "Opened October 16, 1923 as Lou Bard's Hollywood Theatre, featuring a Spanish Revival exterior and an elaborate Egyptian-style interior influenced by the 1922 discovery of Tutankhamen's tomb. Filmmaker Quentin Tarantino purchased it in 2021 and reopened it in 2023 with fully restored 35mm, 70mm, and VistaVision projection capabilities.",
    url: "https://www.vintagecinemas.com/vista/",
    scheduleUrl: "https://www.vintagecinemas.com/vista/",
    searchUrl: (title, date) =>
      `https://www.google.com/search?q=${encodeURIComponent(title + ' showtimes Vista Theatre Los Feliz')}`,
  },
  {
    name: "The Landmark",
    neighborhood: "West LA",
    type: "arthouse",
    note: "12-screen indie & specialty house",
    opened: 1966,
    history: "Originally opened in 1966 as a Laemmle Theatres house in the Westwood area. After renovation in 2019 it was rebranded under the Landmark banner with upgraded seating and a bar. The 12-screen complex on West Pico Boulevard is Landmark's Los Angeles flagship, specializing in independent, foreign, and specialty releases.",
    url: "https://www.landmarktheatres.com/los-angeles/landmark",
    scheduleUrl: "https://www.landmarktheatres.com/los-angeles/landmark",
    searchUrl: (title, date) =>
      `https://www.landmarktheatres.com/los-angeles/landmark`,
  },
  {
    name: "Alamo Drafthouse DTLA",
    neighborhood: "Downtown",
    type: "mainstream",
    note: "Curated programming + mainstream",
    opened: 2019,
    history: "Opened July 2019 on the top floor of The Bloc, a downtown LA shopping complex. The 12-screen, 569-seat venue includes a screen equipped for 35mm projection and is part of the Alamo Drafthouse chain known for its dine-in format, craft drinks, and strict no-talking/no-phones policy. It offers both mainstream releases and curated specialty programming.",
    url: "https://drafthouse.com/los-angeles",
    scheduleUrl: "https://drafthouse.com/los-angeles",
    searchUrl: (title, date) => `https://drafthouse.com/los-angeles`,
  },
];
