const LA_THEATERS = [
  {
    name: "Brain Dead Studios",
    neighborhood: "Fairfax",
    type: "repertory",
    note: "Nightly one-off screenings — indie, cult & classics",
    url: "https://studios.wearebraindead.com",
    scheduleUrl: "https://studios.wearebraindead.com",
    searchUrl: (title, date) => `https://studios.wearebraindead.com`,
  },
  {
    name: "Academy Museum",
    neighborhood: "Mid-Wilshire",
    type: "arthouse",
    note: "Theatrical screenings at the Academy Museum of Motion Pictures",
    url: "https://www.academymuseum.org/en/calendar",
    scheduleUrl: "https://www.academymuseum.org/en/calendar",
    searchUrl: (title, date) => `https://www.academymuseum.org/en/calendar`,
  },
  {
    name: "New Beverly Cinema",
    neighborhood: "Mid-Wilshire",
    type: "repertory",
    note: "Quentin Tarantino's 35mm repertory house",
    url: "https://www.thenewbev.com/",
    scheduleUrl: "https://www.thenewbev.com/",
    searchUrl: (title, date) => `https://www.thenewbev.com/`,
  },
  {
    name: "Egyptian Theatre",
    neighborhood: "Hollywood",
    type: "repertory",
    note: "American Cinematheque — classic & foreign film",
    url: "https://www.americancinematheque.com/egyptian-theatre/",
    scheduleUrl: "https://www.americancinematheque.com/calendar/",
    searchUrl: (title, date) => `https://www.americancinematheque.com/calendar/`,
  },
  {
    name: "Aero Theatre",
    neighborhood: "Santa Monica",
    type: "repertory",
    note: "American Cinematheque on the Westside",
    url: "https://www.americancinematheque.com/aero-theatre/",
    scheduleUrl: "https://www.americancinematheque.com/calendar/",
    searchUrl: (title, date) => `https://www.americancinematheque.com/calendar/`,
  },
  {
    name: "Los Feliz 3",
    neighborhood: "Los Feliz",
    type: "repertory",
    note: "American Cinematheque — classic & foreign film",
    url: "https://www.americancinematheque.com/los-feliz-theatre/",
    scheduleUrl: "https://www.americancinematheque.com/calendar/",
    searchUrl: (title, date) => `https://www.americancinematheque.com/calendar/`,
  },
  {
    name: "Nuart Theatre",
    neighborhood: "West LA",
    type: "arthouse",
    note: "Landmark Theatres' LA flagship",
    url: "https://www.landmarktheatres.com/los-angeles/nuart-theatre",
    scheduleUrl: "https://www.landmarktheatres.com/los-angeles/nuart-theatre",
    searchUrl: (title, date) =>
      `https://www.google.com/search?q=${encodeURIComponent(title + ' showtimes Nuart Theatre')}`,
  },
  {
    name: "Vista Theatre",
    neighborhood: "Los Feliz",
    type: "arthouse",
    note: "1923 single-screen gem, owned by Tarantino",
    url: "https://www.vintagecinemas.com/vista/",
    scheduleUrl: "https://www.vintagecinemas.com/vista/",
    searchUrl: (title, date) =>
      `https://www.google.com/search?q=${encodeURIComponent(title + ' showtimes Vista Theatre Los Feliz')}`,
  },
  {
    name: "The Landmark",
    neighborhood: "West LA",
    type: "arthouse",
    note: "12-screen indie & specialty house",
    url: "https://www.landmarktheatres.com/los-angeles/landmark",
    scheduleUrl: "https://www.landmarktheatres.com/los-angeles/landmark",
    searchUrl: (title, date) =>
      `https://www.landmarktheatres.com/los-angeles/landmark`,
  },
  {
    name: "Alamo Drafthouse DTLA",
    neighborhood: "Downtown",
    type: "mainstream",
    note: "Curated programming + mainstream",
    url: "https://drafthouse.com/los-angeles",
    scheduleUrl: "https://drafthouse.com/los-angeles",
    searchUrl: (title, date) => `https://drafthouse.com/los-angeles`,
  },
];
